# Generated by Django 5.0.4 on 2024-04-07 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referral_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
